server:
  port: 8080

spring:
  application:
    name: Monica
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/monica
    username: admin
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  check-config-location: true
  type-aliases-package: com.example.monica.entity